// SPDX-License-Identifier: Apache-2.0
use std::rc::Rc;

use haxby_opcodes::Opcode as VmOpcode;

use crate::func_builder::{BasicBlock, FunctionBuilder};

pub enum CompilerOpcode {
    Nop,
    Push(u16),
    Push0,
    Push1,
    PushTrue,
    PushFalse,
    PushBuiltinTy(u8),
    PushRuntimeValue(u8),
    Pop,
    Dup,
    Swap,
    Copy(u8),
    Add,
    Sub,
    Mul,
    Div,
    Rem,
    Neg,
    ShiftLeft,
    ShiftRight,
    Not,
    Equal,
    ReadLocal(u8),
    WriteLocal(u8),
    TypedefLocal(u8),
    ReadNamed(u16),
    WriteNamed(u16),
    TypedefNamed(u16),
    ReadIndex(u8),
    WriteIndex(u8),
    ReadAttribute(u16),
    WriteAttribute(u16),
    ReadUplevel(u8),
    LogicalAnd,
    BitwiseAnd,
    LogicalOr,
    BitwiseOr,
    Xor,
    GreaterThan,
    GreaterThanEqual,
    LessThan,
    LessThanEqual,
    JumpTrue(Rc<BasicBlock>),
    JumpFalse(Rc<BasicBlock>),
    Jump(Rc<BasicBlock>),
    JumpIfArgSupplied(u8, Rc<BasicBlock>),
    Call(u8),
    Return,
    TryEnter(Rc<BasicBlock>),
    TryExit,
    Throw,
    BuildList(u32),
    BuildFunction(u8),
    StoreUplevel(u8),
    BuildStruct,
    BuildEnum,
    BuildMixin,
    BindMethod(u8, u16),
    BindCase(u8, u16),
    IncludeMixin,
    NewEnumVal(u16),
    EnumCheckIsCase(u16),
    EnumExtractPayload,
    TryUnwrapProtocol(u8),
    Isa,
    Import(u16),
    LiftModule,
    LoadDylib(u16),
    Assert(u16),
    Halt,
}

impl CompilerOpcode {
    pub fn is_terminal(&self) -> bool {
        match self {
            Self::Nop => false,
            Self::Push(_) => false,
            Self::Push0 => false,
            Self::Push1 => false,
            Self::PushTrue => false,
            Self::PushFalse => false,
            Self::PushBuiltinTy(_) => false,
            Self::PushRuntimeValue(_) => false,
            Self::Pop => false,
            Self::Dup => false,
            Self::Swap => false,
            Self::Copy(_) => false,
            Self::Add => false,
            Self::Sub => false,
            Self::Mul => false,
            Self::Div => false,
            Self::Rem => false,
            Self::Neg => false,
            Self::ShiftLeft => false,
            Self::ShiftRight => false,
            Self::Not => false,
            Self::Equal => false,
            Self::ReadLocal(_) => false,
            Self::WriteLocal(_) => false,
            Self::TypedefLocal(_) => false,
            Self::ReadNamed(_) => false,
            Self::WriteNamed(_) => false,
            Self::TypedefNamed(_) => false,
            Self::ReadIndex(_) => false,
            Self::WriteIndex(_) => false,
            Self::ReadAttribute(_) => false,
            Self::WriteAttribute(_) => false,
            Self::ReadUplevel(_) => false,
            Self::LogicalAnd => false,
            Self::LogicalOr => false,
            Self::Xor => false,
            Self::BitwiseAnd => false,
            Self::BitwiseOr => false,
            Self::LessThan => false,
            Self::GreaterThan => false,
            Self::LessThanEqual => false,
            Self::GreaterThanEqual => false,
            Self::JumpTrue(_) => false,
            Self::JumpFalse(_) => false,
            Self::Jump(_) => true,
            Self::JumpIfArgSupplied(..) => false,
            Self::Call(_) => false,
            Self::Return => true,
            Self::TryEnter(_) => false,
            Self::TryExit => false,
            Self::Throw => true,
            Self::BuildList(_) => false,
            Self::BuildFunction(_) => false,
            Self::StoreUplevel(_) => false,
            Self::BuildStruct => false,
            Self::BuildEnum => false,
            Self::BuildMixin => false,
            Self::BindMethod(..) => false,
            Self::BindCase(..) => false,
            Self::IncludeMixin => false,
            Self::NewEnumVal(_) => false,
            Self::EnumCheckIsCase(_) => false,
            Self::EnumExtractPayload => false,
            Self::TryUnwrapProtocol(_) => false,
            Self::Isa => false,
            Self::Import(_) => false,
            Self::LiftModule => false,
            Self::LoadDylib(_) => false,
            Self::Assert(_) => false,
            Self::Halt => true,
        }
    }

    pub fn byte_size(&self) -> usize {
        match self {
            Self::Nop => 1,
            Self::Push(_) => 3,
            Self::Push0 => 1,
            Self::Push1 => 1,
            Self::PushTrue => 1,
            Self::PushFalse => 1,
            Self::PushBuiltinTy(_) => 2,
            Self::PushRuntimeValue(_) => 2,
            Self::Pop => 1,
            Self::Dup => 1,
            Self::Swap => 1,
            Self::Copy(_) => 2,
            Self::Add => 1,
            Self::Sub => 1,
            Self::Mul => 1,
            Self::Div => 1,
            Self::Rem => 1,
            Self::Neg => 1,
            Self::ShiftLeft => 1,
            Self::ShiftRight => 1,
            Self::Not => 1,
            Self::Equal => 1,
            Self::ReadLocal(_) => 2,
            Self::WriteLocal(_) => 2,
            Self::TypedefLocal(_) => 2,
            Self::ReadNamed(_) => 3,
            Self::WriteNamed(_) => 3,
            Self::TypedefNamed(_) => 3,
            Self::ReadIndex(_) => 2,
            Self::WriteIndex(_) => 2,
            Self::ReadAttribute(_) => 3,
            Self::WriteAttribute(_) => 3,
            Self::ReadUplevel(_) => 2,
            Self::LogicalAnd => 1,
            Self::LogicalOr => 1,
            Self::Xor => 1,
            Self::BitwiseAnd => 1,
            Self::BitwiseOr => 1,
            Self::GreaterThan => 1,
            Self::LessThan => 1,
            Self::GreaterThanEqual => 1,
            Self::LessThanEqual => 1,
            Self::JumpTrue(_) => 3,
            Self::JumpFalse(_) => 3,
            Self::Jump(_) => 3,
            Self::JumpIfArgSupplied(..) => 4,
            Self::Call(_) => 2,
            Self::Return => 1,
            Self::TryEnter(_) => 3,
            Self::TryExit => 1,
            Self::Throw => 1,
            Self::BuildList(_) => 5,
            Self::BuildFunction(_) => 2,
            Self::StoreUplevel(_) => 2,
            Self::BuildStruct => 1,
            Self::BuildEnum => 1,
            Self::BuildMixin => 1,
            Self::BindMethod(..) => 4,
            Self::BindCase(..) => 4,
            Self::IncludeMixin => 1,
            Self::NewEnumVal(_) => 3,
            Self::EnumCheckIsCase(_) => 3,
            Self::EnumExtractPayload => 1,
            Self::TryUnwrapProtocol(_) => 2,
            Self::Isa => 1,
            Self::Import(_) => 3,
            Self::LiftModule => 1,
            Self::LoadDylib(_) => 3,
            Self::Assert(_) => 3,
            Self::Halt => 1,
        }
    }

    pub fn is_jump_instruction(&self) -> Option<Rc<BasicBlock>> {
        match self {
            Self::TryEnter(dst)
            | Self::JumpIfArgSupplied(_, dst)
            | Self::Jump(dst)
            | Self::JumpTrue(dst)
            | Self::JumpFalse(dst) => Some(dst.clone()),
            _ => None,
        }
    }

    pub fn to_vm_opcode(&self, parent: &FunctionBuilder) -> VmOpcode {
        match self {
            Self::Nop => VmOpcode::Nop,
            Self::Push(v) => VmOpcode::Push(*v),
            Self::Push0 => VmOpcode::Push0,
            Self::Push1 => VmOpcode::Push1,
            Self::PushTrue => VmOpcode::PushTrue,
            Self::PushFalse => VmOpcode::PushFalse,
            Self::PushBuiltinTy(n) => VmOpcode::PushBuiltinTy(*n),
            Self::PushRuntimeValue(n) => VmOpcode::PushRuntimeValue(*n),
            Self::Pop => VmOpcode::Pop,
            Self::Dup => VmOpcode::Dup,
            Self::Swap => VmOpcode::Swap,
            Self::Copy(n) => VmOpcode::Copy(*n),
            Self::Add => VmOpcode::Add,
            Self::Sub => VmOpcode::Sub,
            Self::Mul => VmOpcode::Mul,
            Self::Div => VmOpcode::Div,
            Self::Rem => VmOpcode::Rem,
            Self::Neg => VmOpcode::Neg,
            Self::ShiftLeft => VmOpcode::ShiftLeft,
            Self::ShiftRight => VmOpcode::ShiftRight,
            Self::Not => VmOpcode::Not,
            Self::Equal => VmOpcode::Equal,
            Self::ReadLocal(n) => VmOpcode::ReadLocal(*n),
            Self::WriteLocal(n) => VmOpcode::WriteLocal(*n),
            Self::TypedefLocal(n) => VmOpcode::TypedefLocal(*n),
            Self::ReadNamed(n) => VmOpcode::ReadNamed(*n),
            Self::WriteNamed(n) => VmOpcode::WriteNamed(*n),
            Self::TypedefNamed(n) => VmOpcode::TypedefNamed(*n),
            Self::ReadIndex(n) => VmOpcode::ReadIndex(*n),
            Self::WriteIndex(n) => VmOpcode::WriteIndex(*n),
            Self::ReadAttribute(n) => VmOpcode::ReadAttribute(*n),
            Self::WriteAttribute(n) => VmOpcode::WriteAttribute(*n),
            Self::ReadUplevel(n) => VmOpcode::ReadUplevel(*n),
            Self::LogicalAnd => VmOpcode::LogicalAnd,
            Self::LogicalOr => VmOpcode::LogicalOr,
            Self::Xor => VmOpcode::Xor,
            Self::BitwiseAnd => VmOpcode::BitwiseAnd,
            Self::BitwiseOr => VmOpcode::BitwiseOr,
            Self::GreaterThan => VmOpcode::GreaterThan,
            Self::LessThan => VmOpcode::LessThan,
            Self::GreaterThanEqual => VmOpcode::GreaterThanEqual,
            Self::LessThanEqual => VmOpcode::LessThanEqual,
            Self::JumpTrue(dst) => {
                let offset = parent.offset_of_block(dst).expect("invalid block") - 1;
                VmOpcode::JumpTrue(offset)
            }
            Self::JumpFalse(dst) => {
                let offset = parent.offset_of_block(dst).expect("invalid block") - 1;
                VmOpcode::JumpFalse(offset)
            }
            Self::Jump(dst) => {
                let offset = parent.offset_of_block(dst).expect("invalid block") - 1;
                VmOpcode::Jump(offset)
            }
            Self::JumpIfArgSupplied(arg, dst) => {
                let offset = parent.offset_of_block(dst).expect("invalid block") - 1;
                VmOpcode::JumpIfArgSupplied(*arg, offset)
            }
            Self::Call(n) => VmOpcode::Call(*n),
            Self::Return => VmOpcode::Return,
            Self::TryEnter(dst) => {
                let offset = parent.offset_of_block(dst).expect("invalid block") - 1;
                VmOpcode::TryEnter(offset)
            }
            Self::TryExit => VmOpcode::TryExit,
            Self::Throw => VmOpcode::Throw,
            Self::BuildList(v) => VmOpcode::BuildList(*v),
            Self::BuildFunction(a) => VmOpcode::BuildFunction(*a),
            Self::StoreUplevel(a) => VmOpcode::StoreUplevel(*a),
            Self::BuildStruct => VmOpcode::BuildStruct,
            Self::BuildEnum => VmOpcode::BuildEnum,
            Self::BuildMixin => VmOpcode::BuildMixin,
            Self::BindMethod(x, y) => VmOpcode::BindMethod(*x, *y),
            Self::BindCase(x, y) => VmOpcode::BindCase(*x, *y),
            Self::IncludeMixin => VmOpcode::IncludeMixin,
            Self::NewEnumVal(v) => VmOpcode::NewEnumVal(*v),
            Self::EnumCheckIsCase(v) => VmOpcode::EnumCheckIsCase(*v),
            Self::EnumExtractPayload => VmOpcode::EnumExtractPayload,
            Self::TryUnwrapProtocol(v) => VmOpcode::TryUnwrapProtocol(*v),
            Self::Isa => VmOpcode::Isa,
            Self::Import(v) => VmOpcode::Import(*v),
            Self::LiftModule => VmOpcode::LiftModule,
            Self::LoadDylib(n) => VmOpcode::LoadDylib(*n),
            Self::Assert(v) => VmOpcode::Assert(*v),
            Self::Halt => VmOpcode::Halt,
        }
    }
}
